/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dicewars.states;

import dicewars.Main1;
import dicewars.Settings;
import gameTools.state.State;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;

/**
 *
 * @author ganter
 */
public class MenuState extends State {

    /**
     * Creates new form NewJPanel
     */
    public MenuState() {
        super("MenuState", Settings.SCREEN_WIDTH, Settings.SCREEN_HEIGHT);
        inputManager.addKeyMapping("ESC", KeyEvent.VK_ESCAPE);
        inputManager.addKeyMapping("Settings", KeyEvent.VK_S);
        inputManager.addKeyMapping("Load", KeyEvent.VK_L);
        inputManager.addKeyMapping("Play", KeyEvent.VK_P);
        maxTps=5;
        maxFps=30;        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPlay = new javax.swing.JButton();
        BtnSettings = new javax.swing.JButton();
        BtnQuit = new javax.swing.JButton();

        BtnPlay.setText("Start Game");
        BtnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlayActionPerformed(evt);
            }
        });

        BtnSettings.setText("Settings");
        BtnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSettingsActionPerformed(evt);
            }
        });

        BtnQuit.setText("Quit");
        BtnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSettings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnQuit)
                .addGap(117, 117, 117))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnPlay, BtnQuit, BtnSettings});

    }// </editor-fold>//GEN-END:initComponents

    private void BtnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSettingsActionPerformed
        Main1.getInstance().setState("SettingsState");
    }//GEN-LAST:event_BtnSettingsActionPerformed

    private void BtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlayActionPerformed
        Main1.getInstance().setState("GameState");
    }//GEN-LAST:event_BtnPlayActionPerformed

    private void BtnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuitActionPerformed
        Main1.getInstance().dispatchEvent(new WindowEvent(Main1.getInstance(), WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_BtnQuitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPlay;
    private javax.swing.JButton BtnQuit;
    private javax.swing.JButton BtnSettings;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(State s) {
        if (inputManager.isKeyTyped("ESC")){
            BtnQuitActionPerformed(null);
        }
        if (inputManager.isKeyTyped("Settings")){
            BtnSettingsActionPerformed(null);
        }
        if (inputManager.isKeyTyped("Load")){
            
        }
        if (inputManager.isKeyTyped("Play")){
            BtnPlayActionPerformed(null);
        }
    }

    @Override
    public void render() {
        g.drawImage(Settings.TITLE_SCR_BG, 0, 0, Settings.SCREEN_WIDTH, Settings.SCREEN_HEIGHT, this);
    }
}
