----------------------------------------------------
----------------------------------------------------
-- 
--   EZ CSAK AZ OLVASHATÓSÁG KEDVÉÉRT VAN. NE EZT 
--   ADJUK BE, VAN EGY MÁSIK A MINDENT LÉTREHOZ. (DBexport.sql)
--
----------------------------------------------------
----------------------------------------------------

----------------------------------------------------
-- MAPS
----------------------------------------------------
CREATE TABLE "H664800"."MAPS" 
   (	"MAP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"TERRAIN" LONG NOT NULL ENABLE, 
	 CONSTRAINT "MAPS_PK" PRIMARY KEY ("MAP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS";
  
----------------------------------------------------
-- GAMES
----------------------------------------------------
CREATE TABLE "H664800"."GAMES" 
   (	"GAME_ID" NUMBER(*,0), 
	"CREATED" TIMESTAMP (6), 
	"STATE" VARCHAR2(255), 
	"MAP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PLAYER1_SCORE" NUMBER(*,0), 
	"PLAYER2_SCORE" NUMBER(*,0), 
	"PLAYER3_SCORE" NUMBER(*,0), 
	"PLAYER1" VARCHAR2(255), 
	"PLAYER2" VARCHAR2(255), 
	"PLAYER3" VARCHAR2(255), 
	 CONSTRAINT "GAMES_PK" PRIMARY KEY ("GAME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "NEWTABLE_MAPS_FK" FOREIGN KEY ("MAP_ID")
	  REFERENCES "H664800"."MAPS" ("MAP_ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "GAMES_USER1_FK" FOREIGN KEY ("PLAYER1")
	  REFERENCES "H664800"."USERS" ("UNAME") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "GAMES_USER2_FK" FOREIGN KEY ("PLAYER2")
	  REFERENCES "H664800"."USERS" ("UNAME") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "GAMES_USER3_FK" FOREIGN KEY ("PLAYER3")
	  REFERENCES "H664800"."USERS" ("UNAME") ON DELETE SET NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 

  
----------------------------------------------------
-- USERS
----------------------------------------------------
CREATE TABLE "H664800"."USERS" 
   (	"UNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255) NOT NULL ENABLE, 
	"REAL_NAME" VARCHAR2(255), 
	"AGE" NUMBER(*,0), 
	"WINS" NUMBER(*,0), 
	"DEFEATS" NUMBER(*,0), 
	"POINTS" NUMBER(*,0), 
	"RIGHT_ANSWERS" NUMBER(*,0), 
	"WRONG_ANSWERS" NUMBER(*,0), 
	"RIGHT_TIPS" NUMBER(*,0), 
	"WRONG_TIPS" NUMBER(*,0), 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("UNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "USERS_GAMES_FK" FOREIGN KEY ("CURRENT_GAME")
	  REFERENCES "H664800"."GAMES" ("GAME_ID") ON DELETE SET NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS";
  
----------------------------------------------------
-- QUESTION_TOPICS
----------------------------------------------------
CREATE TABLE "H664800"."QUESTION_TOPICS" 
   (	"TOPIC_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "QUESTION_TOPICS_PK" PRIMARY KEY ("TOPIC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
  
----------------------------------------------------
-- NORMAL QUESTIONS
----------------------------------------------------
CREATE TABLE "H664800"."NORMAL_QUESTIONS" 
   (	"QUESTION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"QUESTION" VARCHAR2(255) NOT NULL ENABLE, 
	"RIGHT_ANSWER" VARCHAR2(255) NOT NULL ENABLE, 
	"ANSWER1" VARCHAR2(255) NOT NULL ENABLE, 
	"ANSWER2" VARCHAR2(255) NOT NULL ENABLE, 
	"ANSWER3" VARCHAR2(255) NOT NULL ENABLE, 
	"TOPIC_ID" NUMBER(*,0), 
	"DIFFICULTY" NUMBER(*,0), 
	"AUTHOR" VARCHAR2(255), 
	 CONSTRAINT "NORMALQUESTIONS_PK" PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "QUESTIONS_TOPICS_FK" FOREIGN KEY ("TOPIC_ID")
	  REFERENCES "H664800"."QUESTION_TOPICS" ("TOPIC_ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "NORMAL_QUESTIONS_USERS_FK" FOREIGN KEY ("AUTHOR")
	  REFERENCES "H664800"."USERS" ("UNAME") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
  
----------------------------------------------------
-- RACE_QUESTIONS
----------------------------------------------------
  CREATE TABLE "H664800"."RACE_QUESTIONS" 
   (	"QUESTION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"QUESTION" VARCHAR2(255), 
	"RIGHT_ANSWER" NUMBER(*,0), 
	"TOPIC_ID" NUMBER(*,0), 
	"AUTHOR" VARCHAR2(255), 
	 CONSTRAINT "RACE_QUESTIONS_PK" PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RACE_QUESTIONS_TOPICS_FK" FOREIGN KEY ("TOPIC_ID")
	  REFERENCES "H664800"."QUESTION_TOPICS" ("TOPIC_ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RACE_QUESTIONS_USERS_FK" FOREIGN KEY ("AUTHOR")
	  REFERENCES "H664800"."USERS" ("UNAME") ON DELETE SET NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

----------------------------------------------------
-- ADS
----------------------------------------------------
CREATE TABLE "H664800"."ADS" 
   (	"AD_ID" NUMBER(*,0), 
	"HTML" LONG, 
	 CONSTRAINT "ADS_PK" PRIMARY KEY ("AD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS";

----------------------------------------------------
-- FORUM_TOPICS
----------------------------------------------------
CREATE TABLE "H664800"."FORUM_TOPICS" 
   (	"TOPIC_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(255), 
	 CONSTRAINT "FORUM_TOPICS_PK" PRIMARY KEY ("TOPIC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS";

----------------------------------------------------
-- FORUM_ENTRIES
----------------------------------------------------
CREATE TABLE "H664800"."FORUM_ENTRIES" 
   (	"COMMENT_ID" NUMBER(*,0), 
	"TEXT" LONG, 
	"DATE" TIMESTAMP (6), 
	"AUTHOR" VARCHAR2(255), 
	"TOPIC_ID" NUMBER(*,0), 
	"REF_COMMENT" NUMBER(*,0), 
	 CONSTRAINT "FORUM_ENTRIES_PK" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FORUM_ENTRIES_USERS_FK" FOREIGN KEY ("AUTHOR")
	  REFERENCES "H664800"."USERS" ("UNAME") ENABLE, 
	 CONSTRAINT "FORUM_ENTRIES_FORUM_TOPICS_FK" FOREIGN KEY ("TOPIC_ID")
	  REFERENCES "H664800"."FORUM_TOPICS" ("TOPIC_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FORUM_ENTRIES_FORUM_ENTRIES_FK" FOREIGN KEY ("COMMENT_ID")
	  REFERENCES "H664800"."FORUM_ENTRIES" ("COMMENT_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS";

